# Generated by Django 4.0.5 on 2023-03-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_productimages_productimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('white', 'Oq'), ('green', 'Yashil'), ('blue', 'kok'), ('red', 'qizil')], default='white', max_length=25),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='specification',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
