# Generated by Django 4.0.5 on 2023-03-24 11:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_cart_alter_product_category_delete_shopping_cart_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='ShoppingCard',
        ),
    ]
