# Generated by Django 4.0.5 on 2023-03-25 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_cart_shoppingcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Марка автозапчасти')),
            ],
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50, verbose_name='Модель марки')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
        migrations.CreateModel(
            name='BrandsAndModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.brands', verbose_name='Марка автомобиля')),
                ('id_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.models', verbose_name='Модель')),
            ],
        ),
    ]
