# Generated by Django 4.0.5 on 2023-03-26 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_brands_models_remove_product_type_brandsandmodels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandsandmodels',
            name='id_brand',
        ),
        migrations.RemoveField(
            model_name='brandsandmodels',
            name='id_model',
        ),
        migrations.DeleteModel(
            name='Brands',
        ),
        migrations.DeleteModel(
            name='BrandsAndModels',
        ),
        migrations.DeleteModel(
            name='Models',
        ),
    ]
