# Generated by Django 4.0.5 on 2023-03-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='used_token',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
