# Generated by Django 4.0.5 on 2023-03-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_users_used_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='type',
            field=models.CharField(choices=[('admin', 'Admin'), ('client', 'Client'), ('vip_client', 'VIP Client'), ('merchant', 'Merchant')], default='client', max_length=11),
        ),
    ]
