# Generated by Django 4.0.5 on 2023-03-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_users_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='type',
            field=models.CharField(choices=[('admin', 'Admin'), ('client', 'Client'), ('vip_client', 'VIP Client')], default='client', max_length=11),
        ),
    ]
